### ISSUE TITLE
Review "Configuring LDAP user registries in Liberty" to check for missing info in OL docs

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#5044]
Check through this topic:

https://ibmdocs-test.mybluemix.net/docs/en/SSAW57_liberty_test?topic=liberty-configuring-ldap-user-registries-in

to be sure all pertinent info has been moved to OL- the LDAP and federated user registry features pages

**Comment by dmuelle** [comment]
comments from analysis:

(1) Info in overview https://openliberty.io/docs/21.0.0.5/user-registries-application-security.html and 
(2) feature topic at https://www.openliberty.io/docs/21.0.0.11/reference/feature/ldapRegistry-3.0.html  
(2a) transportSecurity reference missing. 
(2b) Change .jks to .p12. 
(2c) Mention securityUtility encode command to encode the bindPassword password. 
(2d) Missing ClassCastException info. 
(2e) Add explanation: A search base specifies the sub tree of the LDAP server for the search call of the given entity type, which overrides the base DN in search operations. For example, ... 
(2f) Add important note. (
2g) Add: A search base specifies the sub tree of the LDAP server for the search call of the given entity type, which overrides the base DN in search operations. For example,..... 
(2h) Look at what else can be moved to OL.... 12/2/21 
(1) ClassCastException- have it in a troubleshootint section.... 
(2) Needs more analysis as to what should move over. Discuss with Ut's/Ajay's etc  security team.
 (3) Open issue for the "Open Liberty web site" link. IF possible, make it not have the external page. And if necessary, take it up with IBM Docs corporate team.
 (4) Some examples are likely in Federated user registry and LDAP.

**Comment by dmuelle** [comment]
- [x] on [User registries:LDAP user registries for applications in production](https://openliberty.io/docs/21.0.0.5/user-registries-application-security.html#_ldap_user_registries_for_applications_in_production), the link to the Transport security feature is broken.
- [x] [In the Configure a secure connection with LDAPS](https://draft-openlibertyio.mybluemix.net/docs/22.0.0.4/reference/feature/ldapRegistry-3.0.html#ldaps) example, change the keystore files from `.jks` to `.p12` and change `type="JKS"` to `type="PKCS12"`
- [x] In the [Configure an LDAP user registry](https://draft-openlibertyio.mybluemix.net/docs/22.0.0.4/reference/feature/ldapRegistry-3.0.html#simple) example, mention that you can use securityUtility encode command to encode the bindPassword password and provide a link to the command doc. See end of step 4 in IBM docs topic.
- [x]  In the [Configure an LDAP user registry](https://draft-openlibertyio.mybluemix.net/docs/22.0.0.4/reference/feature/ldapRegistry-3.0.html#simple) example, fix broken link to troubleshooting security topic
- [x] add the two sentences about ClassCastException in the IBM Docs topic to the [Specify custom LDAP object classes](https://draft-openlibertyio.mybluemix.net/docs/22.0.0.4/reference/feature/ldapRegistry-3.0.html#object) example
- [x] Add explanation: "A search base specifies the sub tree of the LDAP server for the search call of the given entity type, which overrides the base DN in search operations. For example, ..." from IBM Docs topic to the  [Specify custom LDAP object classes](https://draft-openlibertyio.mybluemix.net/docs/22.0.0.4/reference/feature/ldapRegistry-3.0.html#object) example. Also inlude the `Important` note, but not as a note.
- [x] MIgrate examples in steps 5, 6, 9, 10 and 13 from IBM Docs topic
- [x] Add info from notes in steps 11 and 12 to the [Troubleshooting Security:LDAP](https://openliberty.io/docs/22.0.0.3/troubleshooting.html#Troubleshooting_LDAP) topic.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Corrections Done :
1. Fixed the link to the Transport security feature.
    Link: https://draft-openlibertyio.mybluemix.net/docs/22.0.0.4/user-registries-application-security.html#_ldap_user_registries_for_applications_in_production

2. change the keystore files from `.jks` to `.p12` and change `type="JKS"` to `type="PKCS12"`
Link: https://draft-openlibertyio.mybluemix.net/docs/22.0.0.4/reference/feature/ldapRegistry-3.0.html#ldaps

3. to 7.
Link: https://draft-openlibertyio.mybluemix.net/docs/22.0.0.4/reference/feature/ldapRegistry-3.0.html

8. Add info from notes in steps 11 and 12 to the [Troubleshooting Security:LDAP](https://openliberty.io/docs/22.0.0.3/troubleshooting.html#Troubleshooting_LDAP) topic.
Link: https://draft-openlibertyio.mybluemix.net/docs/22.0.0.4/troubleshooting.html#Troubleshooting_LDAP

Regards,
Ramkumar

**Comment by dmuelle** [comment]
1. LGTM
2. LGTM
3.  to 7.- lets discuss on a call
4. These notes need a descriptive heading like the rest of the content in the section. Look at the original context in IBM docs and add a heading accordingly. Also, run acrolinx on them, I see a few things to fix. Make sure not to start sentences w/ "It is.." or "There are.."

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

For Review : 
https://draft-openlibertyio.mybluemix.net/docs/22.0.0.5/reference/feature/ldapRegistry-3.0.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
## Peer review

- remove extra heading for "Configure failover for multiple LDAP servers"
- fix link to troubleshooting
- remove monospace formatting from anchor link to [Define mapping between LDAP attributes and the user registry externalId attribute](https://docs-draft-openlibertyio.mybluemix.net/docs/22.0.0.5/reference/feature/ldapRegistry-3.0.html#mapldapuserreg)

### Configure an LDAP user registry
- sentence after example needs a capital letter to start
- replace any references to "the tool" with "the command"

### Specify custom LDAP object classes
- needs review:  "In other cases, the user is not found or a request to getSecurityName returns an empty string." What does this mean?
- what is this an example of? 
> For example, java.lang.ClassCastException: com.ibm.wsspi.security.wim.model.Entity is not compatible with com.ibm.wsspi.security.wim.model.LoginAccount. 
Also, formatting is not correct in the example, makes it hard to read
- suggested edit
> A search base specifies the sub tree of the LDAP server for the search call of the given entity type
--->
> The `searchBase` attribute specifies the sub tree of the LDAP server for the search call of the given entity type
- This explanation doesn't line up with the example- either the explanation or example needs to be edited so they have the same values
> You can define a group ldapEntityType searchBase as ou=groups,o=acme.com,c=us. With this definition, entities in other sub trees, such as ou=iThings,o=ibm,c=us, are ignored.
- rewrite with active voice
> Multiple search bases should be used instead of creating multiple LDAP registries for the same LDAP server with different baseDNs.
- This sentence and the paragraph after is duplicated  in the Federated section, remove fvrom this section
> When you use multiple federated LDAP repositories, each repository must define a unique baseDN.... 


### Federate LDAP user registries
- move the new example to be before the existing one. after the first two sentences in this section, move all the new content that starts with "If multiple LDAP registries are configured ..." so that it comes right after the second sentence that ends "...enable the Federated User Registry feature and configure the federatedRepository element."  You might need to edit the text so that it flows well and is not repetitive or seemingly contradictory.
- edit suggestion
> The following example shows two LDAP registries that are federated using a federatedRepository element. 
--->
> The following example shows two LDAP registries that are automatically federated, with configuration that is specified in the federatedRepository element. 
- move the rest of this explanation to after the example
- move the paragraph that starts "It is best practice..." to be before the example, directly after the sentence that ends "...each repository must define a unique baseDN attribute."
- Rewrite any sentences that start with explicative constructions like  "It is.." or "There are..."
- suggested edit
> ...must be the same as the value of baseDN attribute
--->
> ...must be the same as the value of the baseDN attribute
- " It is optional to specify the name attribute. " Which name attribute?
- suggested edit:
> If the name attribute is specified in the ldapRegistry element, then the name attribute in the participatingBaseEntry element must use the same value as the name attribute in the ldapRegistry element.
--->
> The name attribute for the ldapRegistry element is optional. If this attribute is specified, the value of the name attribute in the participatingBaseEntry element must match the value of the name attribute in the ldapRegistry element. If the name attribute in the ldapRegistry element is not specified, the value of the name attribute in the participatingBaseEntry element must match the value of the  baseDN attribute in the ldapRegistry element. Each of these options is demonstrated on one of the participatingBaseEntry element configurations in the previous example.

### Configure certificate filter mode for the LDAP server
- suggested edits
> To use a specified certificate filter for the mapping, you can use the certificateFilter mapping mode
--->
> To use a specified certificate filter for the mapping, you can specify the `CERTIFICATE_FILTER` mapping mode.

> The following example shows an LDAP configuration with the certificate filter mode enabled.
--->
> The following example shows an LDAP configuration with the certificate filter mode enabled by the `certificateMapMode` attribute and a certificate filter that is specified by the `certificateFilter` attribute.

### Define mapping between LDAP attributes and the user registry schema attributes
recommend rewriting the description to be more clear and concise

### Define mapping between LDAP attributes and the user registry externalId attribute
This is almost exactly the same a s the previous example and could be under that same heading. Also why is `autoGenerate="false"` specified if that's the default? Recommend removing it from the example.

### Configure failover for multiple LDAP servers
this needs an introduction/explanation

### Configure SSL configuration to connect to the LDAP server

> The SSL configuration that is used to connect to the LDAP server can be determined in the SSL configuration rather than by being specified with the sslRef attribute. The sslEnabled attribute needs to be set to true. If sslRef attribute is not specified the SSL code looks to see if an outbound filter that matches the LDAP host and port, or if the SSL outbound default should be used.
--->
>  You can specify the SSL configuration that is used to connect to the LDAP server in the SSL configuration instead of using  the sslRef attribute.  Set the sslEnabled attribute to true. If the sslRef attribute is not specified, the SSL code looks for an outbound filter that matches the LDAP host and port. If no matching filter exists,the SSL outbound default is used.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Review Comments incorporated.Please check:

https://draft-openlibertyio.mybluemix.net/docs/22.0.0.5/reference/feature/ldapRegistry-3.0.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
looks good- a few more suggestions

## Specify custom LDAP object classes
- put the java.lang.ClassCastException example in a codeblock 
- suggested edit:

> You can use multiple search bases instead of creating multiple LDAP registries for the same LDAP server with different baseDNs.
--->
> Use LDAP entities to specify multiple search bases instead of creating multiple LDAP registries with different baseDNs for the same LDAP server.

- after you edit this sentence, move it up before the example so that it is the last sentence in the introductory paragraph for the section

- remove the paragraph that starts "It is best practice..."  and the one that follows it as they already rightfully appear under the federated section. 

## Federate LDAP user registries
- rewrite this sentence to remove "It is" expletive construction- "It is best practice, but not mandatory..."
- the first two paragraphs after the example are still really confusing and repeat information needlessly. They also contain typos. Review the two paragraphs and consolidate so they are clear and do not contain duplicated information or errors.
- move this sentence to after the second federated example: "For more information, see [User Registry Federation](https://draft-openlibertyio.mybluemix.net/docs/latest/reference/config/federatedRepository.html)."
- remove unneeded comma:
> Set the allowOpIfRepoDown attribute on the primaryRealm subelement to true, to avoid failures if any user registry is unavailable.
-->
> Set the allowOpIfRepoDown attribute on the primaryRealm subelement to `true` to avoid failures if any user registry is unavailable.

## Define mapping between LDAP attributes and the user registry schema attributes
- remove future tense from the description (will be...)
- "In the following example, ~~you can see that~~ the mapping is defined..."
- this is a sentence fragment and Im not sure what it's supposed to mean

> Also, the mapping that is defined for the externalId user registry attribute with the distinguishedName LDAP attribute for the PersonAccount entity type.

- since this was removed from the example, it should be removed from the description

> The autoGenerate attribute is optional, and the value is false by default.

- the `externalIdAttribute` element in the example is indented to far- make it look like sub elements in other examples
- something is wrong here:

> The following example shows both the primary LDAP server that is specified in the ldapRegistry element. 

- revise to remove expletive construction "There are" in "There are two sets of LDAP ..."

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Review Comments incorporated. Please check:

https://draft-openlibertyio.mybluemix.net/docs/22.0.0.5/reference/feature/ldapRegistry-3.0.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
Looks good- just a few comments

> As a best practice, you can specify the federatedRepository element to federate multiple LDAP registries. Specifying the federatedRepository element is not mandatory, as they are federated automatically

This is better, but still not quite right. The repositories are federated automatically, the element just configures the details of the federation. But that is basically already stated a few lines previous to this paragraph. Notice how much information is repeated in the 4 short paragraphs before the example. I think these could be consolidated into ~2 paragraphs that do not repeat any information. see what you can come up with.

>After the mapping is configured, when you use the user registry attribute for any operation, the value will be equivalent to the value of the LDAP attribute that is mapped.

remove future tense ^^

- the externalIdAttribute element in the example is indented to far- make it look like sub elements in other examples
- something is wrong here:

> The following example shows both the primary LDAP server that is specified in the ldapRegistry element.

**Comment by ramkumar-k-9286** [comment]
Corrections:

As a best practice, you can specify the federatedRepository element to federate multiple LDAP registries. Specifying the federatedRepository element is not mandatory, as they are federated automatically

This is better, but still not quite right. The repositories are federated automatically, the element just configures the details of the federation. But that is basically already stated a few lines previous to this paragraph. Notice how much information is repeated in the 4 short paragraphs before the example. I think these could be consolidated into ~2 paragraphs that do not repeat any information. see what you can come up with.

**Correction:** ---> Consolidated to paragraph 2 
You can adjust the configuration when the the xref:reference:feature/federatedRegistry-1.0.adoc[Federated User Registry] feature is enabled and the `federatedRepository` element is configured.
If you enable the LDAP User Registry feature version 3.0 or later, the Federated User Registry feature is enabled by default.
Otherwise, you must manually enable the Federated User Registry feature and specify the `federatedRepository` element to federate multiple LDAP registries.

-----

After the mapping is configured, when you use the user registry attribute for any operation, the value is equivalent to the value of the LDAP attribute that is mapped.

-----
After the mapping is configured, when you use the user registry attribute for any operation, the value will be equivalent to the value of the LDAP attribute that is mapped.

remove future tense ^^
**Correction:** ---> After the mapping is configured, when you use the user registry attribute for any operation, the value is equivalent to the value of the LDAP attribute that is mapped.

-----
the externalIdAttribute element in the example is indented to far- make it look like sub elements in other examples

**Correction:** ---> 
left aligned the example block

-----
something is wrong here:

The following example shows both the primary LDAP server that is specified in the `ldapRegistry` element.

**Correction:** ---> The following example shows you both the primary LDAP server and two sets of LDAP `failoverServers` elements specified in the `ldapRegistry` element.

**Comment by dmuelle** [comment]
## Federate LDAP user registries

I think we can combine the first an third paragraphs here as they both  start with the same information- the repositories are federated automatically. I think you could remove the first sentence of the 3rd paragraph and add the rest to the first paragraph.  Also some of the info in the second paragraph is not precise- suggested edit:

> LDAP user registries are federated by default. If you configure more than one LDAP user registry in your `server.xml` file, they are automatically federated into a common user registry. Ensure that the users are unique across all federated repositories, otherwise the user registry operations are not successful. When you use multiple federated LDAP registries, each repository must define a unique baseDN attribute.

> You can adjust the configuration of federated registries when the the [Federated User Registry](https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/federatedRegistry-1.0.html) feature is enabled by specifying  the `federatedRepository` element. If you enable the LDAP User Registry feature version 3.0 or later, the Federated User Registry feature is enabled by default. Otherwise, you must manually enable the Federated User Registry feature to use the  `federatedRepository` element.

> If the `federatedRepository` element is specified to configure the...

the externalIdAttribute element in the example is still indented too far- I think it should line up to start directly beneath the `b` in `attribute name`

The rest looks good!

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Review Comments incorporated. Please check:

https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/ldapRegistry-3.0.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
## Configure certificate filter mode for the LDAP server
I think we need to rework this- it's confusing and feature-focused. It's alsoi missing info that can be found on https://ibmdocs-test.mybluemix.net/docs/en/SSAW57_liberty_test?topic=liberty-ldap-certificate-map-mode

Something like:

**Define mapping between client certificate attributes and LDAP user registry attributes**
To map attributes from a client X.509 certificate to attributes in your LDAP configuration, you can specify the CERTIFICATE_FILTER mapping mode. 

If more than one LDAP entry matches the filter specification at run time, authentication fails because the result is an ambiguous match. The syntax for this filter is: `LDAP attribute=${Client certificate attribute}`

An example of a simple certificate filter is `uid=${SubjectCN}`.

You can also specify multiple properties and values as part of a certificate filter. The LDAP attribute of the filter specification depends on the schema that your LDAP server is configured to use. The client certificate attribute is one of the public attributes in your client certificate. The client certificate attribute must begin with a dollar sign, $, and opening brace, {, and end with a closing brace, }. The attributes are case-sensitive.

The following LDAP attributes are supported:
uid
initials
sAMAccountName
displayName
distinguishedName
displayName
description

The following client certificate attributes are supported:
${SubjectCN}
${SubjectDN}
${IssuerCN}
${IssuerDN}
${SerialNumber}

The following example shows an LDAP configuration with the certificate filter mode that is enabled by the `certificateMapMode` attribute and a certificate filter that is specified by the` certificateFilter` attribute. In this certificate filter configuration, the value for the `uid` LDAP attribute to the `${SubjectCN}` client certificate attribute.

[EXAMPLE]

For more information, see `certificateFilter` and `certificateMapMode` in [LDAP User Registry](https://draft-openlibertyio.mybluemix.net/docs/latest/reference/config/ldapRegistry.html)

**Comment by dmuelle** [comment]
## Define mapping between LDAP attributes and the user registry schema attributes
For the example in this section- the `attribute` and ` externalIdAttribute`  elements should have the same indent. They should both line up under the "b" of the `attributeConfiguration` element.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Comments incorporated. 

Draft link: https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/ldapRegistry-3.0.html

Regards,
Ramkumar

**Comment by ramkumar-k-9286** [comment]
the `attribute` and `externalIdAttribute` elements should have the same indent.  -  Seems fixed now.
 
Draft link: https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/ldapRegistry-3.0.html

but found similar issues for:
https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/ldapRegistry-3.0.html#federate

in the second code block.

Will be correcting that as well.

Regards,
Ramkumar

**Comment by dmuelle** [comment]
ok- note also that the lists in this example intro are still not rendering:

https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/ldapRegistry-3.0.html#Certfilter

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Corrections done.

Fixed the intent issue:
https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/ldapRegistry-3.0.html#federate

Fixed the lists in the cert filter:
https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/ldapRegistry-3.0.html#Certfilter


Regards,
Ramkumar

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Suggested corrections were done to the page. ( removed 2 bulleted lists, also text edits (`${SubjectCN}`).

https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/ldapRegistry-3.0.html#Certfilter

Regards,
Ramkumar

**Comment by dmuelle** [comment]
looks better- 2 minor nits:

The client certificate attribute must begin with a dollar sign, $, and must be enclosed within braces, {}, like `${SubjectCN}`.
--->
The client certificate attribute must begin with a dollar sign and must be enclosed in braces, for example, `${SubjectCN}`.


The LDAP attributes that are supported are `uid`, `initials`, `sAMAccountName`,` displayName`, `distinguishedName`, `displayName` and `description`.
--->
The following LDAP attributes that are supported:`uid`, `initials`, `sAMAccountName`,` displayName`, `distinguishedName`, `displayName`, and `description`.

The other attribute list needs a similar revision. Don't forget to add comma before "and" in a list.

**Comment by ramkumar-k-9286** [comment]
Hi Jesse @jvanhill 

As a part of moving information from WL to OL. We had moved information regarding LDAP.

Source: https://ibmdocs-test.mybluemix.net/docs/en/SSAW57_liberty_test?topic=liberty-configuring-ldap-user-registries-in

The sections where edits have been made are as follows.

https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/ldapRegistry-3.0.html#Certfilter

https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/ldapRegistry-3.0.html#mapldapattributes

https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/ldapRegistry-3.0.html#configurefailover

Could you please review these sections? provide us with feedback on the same. 

Regards,
Ramkumar

cc @dmuelle

**Comment by jvanhill** [comment]
@ramkumar-k-9286 -

I noticed this section (https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/ldapRegistry-3.0.html#configuresslconfiguration). That should probably be combined with this section (https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/ldapRegistry-3.0.html#ldaps).

Otherwise looks good.

**Comment by ramkumar-k-9286** [comment]
Hi Jesse @jvanhill

Based on your suggestions, we have merged the sections. Please check and let us know if you are ok with the changes that have been made.

Link: https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/ldapRegistry-3.0.html#ldaps

Regards,
Ramkumar

CC @dmuelle

**Comment by dmuelle** [comment]
LGTM

**Comment by ramkumar-k-9286** [comment]
Communication with Jesse
--

Actually, sorry... the second section about using an outbound SSL filter can probably be improved.


<ldapRegistry ... host="ldapserver.mycity.mycompany.com" port="389" sslEnabled="true" >
    ...
</ldapRegistry>

<ssl id="LdapSSLSettings" keyStoreRef="LDAPKeyStore" trustStoreRef="LDAPTrustStore" >
    <outboundConnection host="ldapserver.mycity.mycompany.com" port="389" />
</ssl>
<keyStore id="LDAPKeyStore" location="server1/resources/security/key.p12" type="PKCS12" password="password" />
<keyStore id="LDAPTrustStore" location="server1/resources/security/trust.p12" type="PKCS12" password="password" />


it doesn't show how to set the outbound connection for SSL

and there is no reason to show all the other attributes and settings, it just gets confusing.

instead, I just put ellipses in there to indicate there is more configuration.

We should update this next release perhaps.

The first config block should probably also be updated...

<ldapRegistry ... sslEnabled="true" sslRef="LDAPSSLSettings" >
   ...
</ldapRegistry>

<ssl id="LDAPSSLSettings" keyStoreRef="LDAPKeyStore" trustStoreRef="LDAPTrustStore" />
<keyStore id="LDAPKeyStore" location="server1/resources/security/key.p12" type="PKCS12" password="password" />
<keyStore id="LDAPTrustStore" location="server1/resources/security/trust.p12" type="PKCS12" password="password" />

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Based on SME suggestions, I replaced the examples in the **secure connection with LDAPS** sections. Please check and let us know if you are ok with the changes that have been made.

Link: https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/ldapRegistry-3.0.html#ldaps

Regards,
Ramkumar

**Comment by dmuelle** [comment]
I think it's ok to reduce the extra config but what is being left out here might be confusing. We should make the two examples more alike and then explain the differences.

First, move the more information link to the first paragraph under this example
---

> To enable a secure connection to an LDAP server for encrypted communication by way of TLS or SSL protocols, configure the ldapRegistry element to enable Lightweight Directory Access Protocol Over Secure Socket Links (LDAPS). Set the sslEnabled attribute to true and the sslRef attribute to your ssl id value. To enable a secure TLS or SSL connection, you must configure these connections in the ssl element. _For more information about TLS and SSL configurations, see [SSL Repertoire](https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/config/ssl.html)._ 

(emphasis for demonstration only)

Then standardize and the examples and explain them more clearly, something like:
---
The following example shows both the ldapRegistry element and the ssl element that the LDAP connection references....etc

```xml
<ldapRegistry host="ldapserver.mycity.mycompany.com" port="389" 
                         sslEnabled="true" sslRef="LDAPSSLSettings"..../ >

<ssl id="LDAPSSLSettings" keyStoreRef="LDAPKeyStore" trustStoreRef="LDAPTrustStore" />
<keyStore id="LDAPKeyStore" location="server1/resources/security/key.p12" type="PKCS12" password="password" />
<keyStore id="LDAPTrustStore" location="server1/resources/security/trust.p12" type="PKCS12" password="password" />
```

Alternatively, you can enable  the SSL configuration that is used to connect to the LDAP server without specifying the `sslRef` attribute. When the `sslEnabled` attribute is set to `true` and the `sslRef` attribute is not specified, the SSL code looks for an outbound filter that matches the LDAP host and port. If no matching filter exists, the SSL outbound default is used. In the following example, SSL is enabled but the `sslRef` attribute is not specified, so LDAP 
uses the `LdapSSLSettings` SSL configuration, which specifies the same host and port as the `ldapRegistry` configuration.

```xml
<ldapRegistry host="ldapserver.mycity.mycompany.com" port="389" sslEnabled="true"... / >

<ssl id="LdapSSLSettings" keyStoreRef="LDAPKeyStore" trustStoreRef="LDAPTrustStore" >
    <outboundConnection host="ldapserver.mycity.mycompany.com" port="389" />
</ssl>
<keyStore id="LDAPKeyStore" location="server1/resources/security/key.p12" type="PKCS12" password="password" />
<keyStore id="LDAPTrustStore" location="server1/resources/security/trust.p12" type="PKCS12" password="password" />
```

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Corrections have been done based on the suggestions provided.

Link: https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/ldapRegistry-3.0.html#ldaps

Regards,
Ramkumar

**Comment by dmuelle** [comment]
looks good except for one very minor thing- acriolinx is finding the first sentence as too long. I think you could fix it simple by replacing "by way of" to "with"

**Comment by dmuelle** [comment]
changes are on vNext and will publish with 22.0.0.7
