### ISSUE TITLE
replaceAll operation (?) made KC article unusable

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/docs#726]
This is reported on mutliple channels on Slack.   Please help retrieve the history and get it back to the meaningful doc.  Thanks!  (was-security, was-random 10/11) 

https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/twlp_sec_ssl.html

For example... (but not limited to this specific paragraph..) 
Due to the nature of the JDK, i**f you are changing from the transportSecurity-1.0 feature to the transportSecurity-1.0 feature or from the transportSecurity-1.0 feature to the transportSecurity-1.0 feature,** the Liberty server must be restarted to use the feature to its complete functionality.

**Comment by lauracowen** [comment]
I believe this has already been fixed in the KC: https://github.ibm.com/was-liberty/liberty-docs/issues/1586

@dmuelle - can you confirm?

**Comment by dmuelle** [comment]
@lauracowen @una-tapa yes this was corrected and the updated doc went to production with 19.0.0.11 on 11/15

https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/twlp_sec_ssl.html

**Comment by una-tapa** [comment]
The updated article looks good. Thanks, David & Laura!

**Comment by una-tapa** [comment]
I got Slack message from our L2 and was checking this doc issue again.  

Following page (discussed in this issue) is still incorrect. 
https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/twlp_sec_ssl.html

The bullet 1 used to be about ssl-1.0 feature and bullet 2 is about transport-1.0 feature.
But in the current doc,  both of them talks about transport-1.0 feature so it is very strange when bullet 2 says `SSL communication can alternately be enabled by adding the transportSecurity-1.0 ` when bullet 1 talks about transportSecurity-1.0 already.  

```
Procedure
1.  Enable the transportSecurity-1.0 Liberty feature in the server.xml file.
<featureManager>
    <feature>transportSecurity-1.0</feature>
</featureManager>Copy
Note
If application security is required and security information is redirected to a secure port, you must add the appSecurity-2.0 Liberty feature to the server.xml file.
When the transportSecurity-1.0 feature is enabled, the Liberty server creates an SSLContext from the default SSL configuration and makes that SSLContext the server default by calling the SSLContext.setDefault() java API. This makes the default SSLContext of the Liberty server the process default SSLContext. If anything makes the Java™ API call SSLContext.getDefault(), then the method returns Liberty SSLContext. The same applies to the SSLSocketFactory.getDefault() Java™ API in that the default socket factory from the default SSLContext is returned.

2.  SSL communication can alternately be enabled by adding the transportSecurity-1.0 Liberty feature in the server.xml file.
<featureManager>
    <feature>transportSecurity-1.0</feature>
</featureManager>Copy
The transportSecurity-1.0 feature supersedes the ssl-1.0 feature a.... 
```

Our L2 is asking about another page that is also wrong for the same topic.  She is pointing contradicting sentences in the same page.    In this case,  I think following line is wrong, because SSLContext does get set by ssl-1.0 feature. 

>> The Liberty SSL runtime code does not set the SSLContext process default when the transportSecurity-1.0 or ssl-1.0 features are enabled

```
Andrea Pichler  5 hours ago
SSL advice requested:
The SSL defaults in Liberty page (https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/rwlp_liberty_ssl_defaults.html) appears to contradict itself:
Under "The (transportSecurity-1.0) behavior" it states:
The Liberty SSL runtime code does not set the SSLContext process default when the transportSecurity-1.0 or ssl-1.0 features are enabled
However, under "The (ssl-1.0) behavior" it states:
That SSLContext is set on the process as the default SSLContext by using the Java API SSLContext.setDefault()
Which is correct? Many thanks in advance! 
``` 

cc: @acdemyers

**Comment by una-tapa** [comment]
cc: @andrea-pichler  Thanks for bringing this up.  Please monitor this issue and update L2 team regularly.  Thanks!

**Comment by acdemyers** [comment]
Did this change?   Anyway the first bullet should be about the ssl-1.0
feature and the second about the transportSecurity-1.0 feature.


Alaine De Myers
WebSphere Security Development
903/4B002, Austin, TX 78751
(512) 286-5922, t/l: 363-5922
alaine@us.ibm.com

**Comment by una-tapa** [comment]
@acdemyers   Thanks for confirmation! 

We got multiple reports from slack, customer that this article is totally broken because ssl-1.0 was `changeAll`ed with transportSecurity-1.0.   I was told it is fixed but the incorrect article is still on the web....

**Comment by dmuelle** [comment]
Hi @acdemyers @unatapa- I edited this page to correct the global find/replace error per another git issue but did not have complete information as to how to correct the problem. Is the following revision correct?

1.  Enable the `ssl-1.0` Liberty feature in the server.xml file.
```
<featureManager>
    <feature>ssl-1.0</feature>
</featureManager>Copy
```
Note
If application security is required and security information is redirected to a secure port, you must add the `appSecurity-2.0` Liberty feature to the server.xml file.

When the `ssl-1.0` feature is enabled, the Liberty server creates an SSLContext from the default SSL configuration and makes that SSLContext the server default by calling the SSLContext.setDefault() java API. This makes the default SSLContext of the Liberty server the process default SSLContext. If anything makes the Java™ API call SSLContext.getDefault(), then the method returns Liberty SSLContext. The same applies to the SSLSocketFactory.getDefault() Java™ API in that the default socket factory from the default SSLContext is returned.

2.  SSL communication can alternately be enabled by adding the `transportSecurity-1.0` Liberty feature in the server.xml file.
```
<featureManager>
    <feature>transportSecurity-1.0</feature>
</featureManager>Copy
```
The `transportSecurity-1.0` feature supersedes the `ssl-1.0` feature a....

**Comment by dmuelle** [comment]
If `transportSecurity-1.0`  supersedes `ssl-1.0` should it be introduced first? Currently, the `About this task` introduction discusses `transportSecurity-1.0`, not `ssl-1.0`. It seems confusing to start the procedure by telling the user to add `ssl-1.0` and then mentioning `transportSecurity-1.0` as an alternative.

**Comment by acdemyers** [comment]
That is correct.


Alaine De Myers
WebSphere Security Development
903/4B002, Austin, TX 78751
(512) 286-5922, t/l: 363-5922
alaine@us.ibm.com

**Comment by andrea-pichler** [comment]
Hi @una-tapa, looking at "Enabling SSL communication in Liberty" 
https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/twlp_sec_ssl.html
"When the transportSecurity-1.0 feature is enabled, the Liberty server creates an SSLContext from the default SSL configuration and makes that SSLContext the server default by calling the SSLContext.setDefault() java API. This makes the default SSLContext of the Liberty server the process default SSLContext. If anything makes the Java™ API call SSLContext.getDefault(), then the method returns Liberty SSLContext. The same applies to the SSLSocketFactory.getDefault() Java™ API in that the default socket factory from the default SSLContext is returned. "

is also contradicting this:
"When the transportSecurity-1.0 feature is enabled, the Liberty server sets a custom SSL Socket factory that uses the Java security property ssl.SocketFactory.provider. This security property is set automatically when the transportSecurity-1.0 feature is enabled. When you are using the transportSecurity-1.0 feature, the process SSLContext is the SSLContext of the Java Secure Socket Extension (JSSE). A call to SSLContext.get() returns the default context SSLContext of the JSSE. A call to SSLSocketFactory.getDefault() returns an SSLSocketFactory that is based on the Liberty server custom socket factory provider that uses the Liberty SSLContext."

Mr. Whale and I (just confirmed) agree that ssl-1.0 calls setDefault() but transport-1.0 does not.. Thanks again!

**Comment by acdemyers** [comment]
I think I when with ssl-1.0 first because it existed first and was the
original behavior of Liberty,  and it is what is brought in when the
appSecurity-* feature are added.  The transportSecurity-1.0 feature and the
alternate behavior came later.   It seem to make send to me at the time.


Alaine De Myers
WebSphere Security Development
903/4B002, Austin, TX 78751
(512) 286-5922, t/l: 363-5922
alaine@us.ibm.com

**Comment by acdemyers** [comment]
The correct wording should be:

"When the ssl-1.0 feature is enabled, the Liberty server creates an
SSLContext from the default SSL configuration and makes that SSLContext the
server default by calling the SSLContext.setDefault() java API. This makes
the default SSLContext of the Liberty server the process default
SSLContext. If anything makes the Java™ API call SSLContext.getDefault(),
then the method returns Liberty SSLContext. The same applies to the
SSLSocketFactory.getDefault() Java™ API in that the default socket factory
from the default SSLContext is returned. "

This is under the first bullet.


Alaine De Myers
WebSphere Security Development
903/4B002, Austin, TX 78751
(512) 286-5922, t/l: 363-5922
alaine@us.ibm.com

**Comment by dmuelle** [comment]
@acdemyers - should this sentence in the `About this task` section be revised?

`To enable SSL in Liberty, you add the transportSecurity-1.0 Liberty feature to the configuration root document file, server.xml, along with code of the keystore information for authentication.`

to 

`To enable SSL in Liberty, you add the ssl-1.0 Liberty feature to the configuration root document file, server.xml, along with code of the keystore information for authentication.`

The page currently states that  `transportSecurity-1.0` supersedes `ssl-1.0` and adds functionality that `ssl-1.0` does not have. But @andrea-pichler comment above says that `ssl-1.0` calls setDefault() but `transport-1.0` does not.

I'm trying to understand the relationship between these two properties so I can get the correct information into the doc- would the user implement one or the other? or both? is one preferred over the other?

Thanks!

**Comment by acdemyers** [comment]
It is an odd thing.  There is this difference in behavior between them, but
architects wanted transportSecurity-1.0 to be a superseed.   I'd argue that
in the majority of cases people can move between the two and would not
notices.   If they application doing some direct SSL calls is where they
may run into a need for one over the other.

In the doc reference I explain the difference between ssl-1.0 and
transportSecurity-1.0.

Some of the new features require transportSecurity-1.0,  like the outbound
filters, outbound default support and hostname verification on ssl
configuration.

The preference it to use transportSecurity-1.0, you get more features.


Alaine De Myers
WebSphere Security Development
903/4B002, Austin, TX 78751
(512) 286-5922, t/l: 363-5922
alaine@us.ibm.com

**Comment by dmuelle** [comment]
@acdemyers thanks for this explanation- I think l I have a better understanding now. I'll work on a new draft this afternoon and share for your review asap

**Comment by dmuelle** [comment]
@acdemyers @andrea-pichler @una-tapa 

I've revised this doc to hopefully fix the remaining errors and clarify the information that is there. You can review the updated doc on our preprod site

https://www-03preprod.ibm.com/support/knowledgecenter/SSAW57_liberty_temp/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_sec_ssl.html

**note that I combined and reorganized steps 1 & 2** since these were not actually distinct sequential steps in the process but instead two alternate ways to achieve the same result (Enabling SSL communication)> I believe that I have preserved the correct contextual information for each of the properties discussed (transport-1.0 and ssl-1.0) and resolved any contradictions. Please let me know if I missed anything.

I'm not sure where this note belongs- 
`If application security is required and security information is redirected to a secure port, you must add the appSecurity-2.0 Liberty feature to the server.xml file.`

Does this apply specifically to `ssl-1.0`? If so, the note does not make this clear. Is there information missing here?

@andrea-pichler re: the other page, `SSL defaults in Liberty`- based on the information here, i think this sentence is incorrect and the cause of the contradiction

`The Liberty SSL runtime code does not set the SSLContext process default when the transportSecurity-1.0 or ssl-1.0 features are enabled.`

I have revised it to

`The Liberty SSL runtime code does not set the SSLContext process default when the transportSecurity-1.0 feature is enabled.`

Here is a preview of the revision
https://www-03preprod.ibm.com/support/knowledgecenter/SSAW57_liberty_temp/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/rwlp_liberty_ssl_defaults.html

Is this correct?


Thanks all, please let me know if this looks ok or if further edits are required.

**Comment by acdemyers** [comment]
Looks good.   Minor update you refer to SSLContext.get() in the section on
transportSecurity-1.0 it should be SSLContext.getDefault().


Alaine De Myers
WebSphere Security Development
903/4B002, Austin, TX 78751
(512) 286-5922, t/l: 363-5922
alaine@us.ibm.com

**Comment by andrea-pichler** [comment]
Hi @dmuelle the change on the `SSL defaults in Liberty` page looks good to me, thank you!

**Comment by dmuelle** [comment]
@acdemyers - I will make that change and rebuild the preview.

Can you offer any insight on the relationship between `ssl-1.0` and `appSecurity-2.0` ? The NOTE that is currently in the doc doesn't seem to give enough info for the user to understand why it's there (in the ssl-1.0 section)

`If application security is required and security information is redirected to a secure port, you must add the appSecurity-2.0 Liberty feature to the server.xml file.`

Is this something that a user who requires security must do in order to add the ssl-1.0 feature? Does adding appSecurity-2.0 also pull in ssl-1.0 or would the user need to add both properties?

Thanks

**Comment by acdemyers** [comment]
The appSecurity-2.0 feature will bring in the ssl-1.0 feature.   I believe
that comment was added a long time ago because some people thought it was
enough to just add ssl-1.0 to make ssl redirect to work on applications,
when you will actually need the appSecurity feature.


Alaine De Myers
WebSphere Security Development
903/4B002, Austin, TX 78751
(512) 286-5922, t/l: 363-5922
alaine@us.ibm.com

**Comment by una-tapa** [comment]
Alaine

Good topic.  I have questions here... 

If appSecurity-2.0 is set with transportSecurity-1.0, Liberty will use it. 

If transportSecurity-1.0 only,  appSecurity-2.0 is not enabled. 

Is the same applies to appSecurity-3.0? 

Hiroko Takamiya
WebSphere Application Server Security,  IBM Corp
4205 S Miami Blvd, Durham NC 27703-9141
E-mail: htakamiy@us.ibm.com

**Comment by dmuelle** [comment]
@acdemyers ok- Would this then be an acceptable revision for this note?

`The ssl-1.0 feature does not enable SSL redirects. If application security is required and security information is redirected to a secure port, you must add the appSecurity-2.0 Liberty feature to the server.xml file. The appSecurity-2.0 feature includes the ssl-1.0 feature. It is not necessary to add both features.`

**Comment by acdemyers** [comment]
If you expect your application to do an ssl redirect then you need
appSecurity* to be included.   If you need the features from
transportSecurity then include it in addition to the appSecurity feature.


Alaine De Myers
WebSphere Security Development
903/4B002, Austin, TX 78751
(512) 286-5922, t/l: 363-5922
alaine@us.ibm.com

**Comment by acdemyers** [comment]
@dmuelle -  Your suggested changes are fine.


Alaine De Myers
WebSphere Security Development
903/4B002, Austin, TX 78751
(512) 286-5922, t/l: 363-5922
alaine@us.ibm.com

**Comment by una-tapa** [comment]
Thanks, Alaine,  I hope this is clarified in the doc.  Is this correct? 
So, if appSecurity is added,  sso-1.0 is automatically pulled in, and 
customer can add transportSecurity-1.0, then transportSecurity-1.0 is 
used, not sso-1.0. 

Hiroko Takamiya
WebSphere Application Server Security,  IBM Corp
4205 S Miami Blvd, Durham NC 27703-9141
E-mail: htakamiy@us.ibm.com

**Comment by dmuelle** [comment]
@acdemyers @una-tapa 

here is an updated preview of the page

https://www-03preprod.ibm.com/support/knowledgecenter/SSAW57_liberty_temp/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_sec_ssl.html

This update fixes the `SSLContext.getDefault()` error that @acdemyers mentions above and clarifies `appSecurity-3.0` vs `ssl-1.0` and `transportSecurity-1.0` in the NOTE

Please review and let me know if further edits are needed. If it looks ok, please add the `Developer reviewed` label to this issue and I'll close it out. Thanks!

**Comment by una-tapa** [comment]
While I think this doc looks much better than previous one,  can we have a short meeting (30 mins) to discuss next week please?  (David and Alaine) 
In our bi-weekly meeting and slack,  I hear a lot of questions and concerns about this page.   Just wanted to get it straightened.

**Comment by dmuelle** [comment]
Sure- just let me know what works for you.

**Comment by dmuelle** [comment]
closing this issue- remaining work will be tracked in the Liberty docs repo at https://github.ibm.com/was-liberty/liberty-docs/issues/1743
